### ISSUE TITLE
Error trying to set configuration

### ISSUE THREAD

**Issue by letterj** [pandemicsyn/syndicate#18]
root@letterj03-aio oort $ syndicate-client rm 4722778942020063540
[rm 4722778942020063540]  
Status:  true
Version: 1452786749239799806
root@letterj03-aio oort $ syndicate-client set config=/etc/oort/valuestore.toml
[set config=/etc/oort/valuestore.toml]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40889f]

goroutine 1 [running]:
main.(_SyndClient).SetConfig(0xc82015c5c0, 0xc82016f200, 0x207, 0x407, 0x400, 0x7effd29982f0, 0xc82015d740)
        /root/go/src/github.com/pandemicsyn/syndicate/syndicate-client/main.go:383 +0x73f
main.(_SyndClient).mainEntry(0xc82015c5c0, 0xc82000a2b0, 0x2, 0x2, 0x0, 0x0)
        /root/go/src/github.com/pandemicsyn/syndicate/syndicate-client/main.go:234 +0xa0e
main.main()
        /root/go/src/github.com/pandemicsyn/syndicate/syndicate-client/main.go:128 +0x823

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 34 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc82017e000)
        /root/go/src/google.golang.org/grpc/clientconn.go:493 +0x1c9
google.golang.org/grpc.NewConn.func1(0xc82017e000)
        /root/go/src/google.golang.org/grpc/clientconn.go:304 +0x1b5
created by google.golang.org/grpc.NewConn
        /root/go/src/google.golang.org/grpc/clientconn.go:305 +0x4fb

goroutine 38 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc8201a8000)
        /root/go/src/google.golang.org/grpc/transport/http2_client.go:817 +0x5d8
created by google.golang.org/grpc/transport.newHTTP2Client
        /root/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x1536

**Comment by letterj** [comment]
Followed up with this:
root@letterj03-aio oort $ syndicate-client search
[search]
Searching for: &proto.Node{Id:0x0, Active:false, Capacity:0x0, Tiers:[]string(nil), Addresses:[]string(nil), Meta:"", Conf:[]uint8(nil)}
rpc error: code = 4 desc = "context deadline exceeded"
root@letterj03-aio oort $ systemctl restart synd
root@letterj03-aio oort $ syndicate-client search
[search]
Searching for: &proto.Node{Id:0x0, Active:false, Capacity:0x0, Tiers:[]string(nil), Addresses:[]string(nil), Meta:"", Conf:[]uint8(nil)}

# result 0

ID:        5217693367355621356
Active:    true
Capacity:  1000
Tiers:     removeme
Addresses: 
Meta:  
Conf:  
root@letterj03-aio oort $ syndicate-client set config=/etc/oort/valuestore.toml 
[set config=/etc/oort/valuestore.toml]
Status:  true
Version: 1452787039203608488
root@letterj03-aio oort $ syndicate-client rm 5217693367355621356
[rm 5217693367355621356]
2016/01/14 15:57:41 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/01/14 15:57:42 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:8443: getsockopt: connection refused"; Reconnecting to "127.0.0.1:8443"
2016/01/14 15:57:43 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:8443: getsockopt: connection refused"; Reconnecting to "127.0.0.1:8443"
2016/01/14 15:57:46 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:8443: getsockopt: connection refused"; Reconnecting to "127.0.0.1:8443"
2016/01/14 15:57:46 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/01/14 15:57:47 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:8443: getsockopt: connection refused"; Reconnecting to "127.0.0.1:8443"
2016/01/14 15:57:49 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:8443: getsockopt: connection refused"; Reconnecting to "127.0.0.1:8443"
rpc error: code = 13 desc = "transport is closing"

**Comment by letterj** [comment]
From the working with the Group Store:
root@letterj03-aio oort $ syndicate-client -addr 127.0.0.1:8444 search
[search]
Searching for: &proto.Node{Id:0x0, Active:false, Capacity:0x0, Tiers:[]string(nil), Addresses:[]string(nil), Meta:"", Conf:[]uint8(nil)}

# result 0

ID:        11866566594092154116
Active:    true
Capacity:  1000
Tiers:     removeme
Addresses: 
Meta:  
Conf:      

# result 1

ID:        7245046733950186427
Active:    false
Capacity:  0
Tiers:     letterj03-aio.rackfs.com
Addresses: 10.176.131.41:8002
Meta:      letterj03-aio.rackfs.com|something
Conf:  
root@letterj03-aio oort $ syndicate-client -addr 127.0.0.1:8444 rm 11866566594092154116
[rm 11866566594092154116]
2016/01/14 16:07:26 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/01/14 16:07:27 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:8444: getsockopt: connection refused"; Reconnecting to "127.0.0.1:8444"
2016/01/14 16:07:29 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:8444: getsockopt: connection refused"; Reconnecting to "127.0.0.1:8444"
2016/01/14 16:07:32 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:8444: getsockopt: connection refused"; Reconnecting to "127.0.0.1:8444"
2016/01/14 16:07:32 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/01/14 16:07:33 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:8444: getsockopt: connection refused"; Reconnecting to "127.0.0.1:8444"
2016/01/14 16:07:34 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:8444: getsockopt: connection refused"; Reconnecting to "127.0.0.1:8444"
rpc error: code = 13 desc = "transport is closing"
